### ISSUE TITLE
Constants file is empty

### ISSUE THREAD

**Issue by swissspidy** [sniccowp/php-scoper-wordpress-excludes#2]
I'd expect `exclude-wordpress-constants.json` to include constants like `WP_CONTENT_DIR` and `WP_CONTENT_URL`. Right now it's completely empty.

**Comment by calvinalkan** [comment]
@swissspidy Hey, 

the file is empty because the maintainer of `php-stubs/wordpress-stubs` [does not want to include](https://github.com/php-stubs/wordpress-stubs/issues/5#issuecomment-568094078) global Wordpress constants in the package.

There is this [list](https://github.com/php-stubs/wordpress-globals/blob/master/wordpress-globals.php) of constants from the same organization that we could use in theory, it's not auto-updated and not [maintained](https://github.com/php-stubs/wordpress-globals/issues/3) very well.

I agree with the guy that directly using the global constants would be avoided in favor of the respective functions.

Realistically, I think the best we can do is use the mentioned list of global constants and generate a list for it that we include here in the repo aswell.

I don't see a way to automate this tho, as the project is still at v0.2. Im open to suggestions tho.

**Comment by calvinalkan** [comment]
@swissspidy I experimented a bit and this seems to work. I created a new --exclude-empty option that could be used when generating the stubs for the `php-stubs/wordpress-globals` package and we would end up with what you currently see in master.

**Comment by swissspidy** [comment]
> I agree with the guy that directly using the global constants would be avoided in favor of the respective functions.

Fair, but in the context of PHP-Scoper where we are scoping our dependencies' code we don't have a choice really :-) It's not our code that's using these constants so we can't do anything about it.

The new file you've created looks promising!

**Comment by calvinalkan** [comment]
Correct, you are right. 

So what do you suggest? The wordpress globals package does not corrolate with the released versions of WordPress. 

What we could do is always include the latest version (currently 0.2.0) of that package with every new tag for the wordpress stubs. 

On another note, do you think we should include the empty files for traits? I initially included them so that people could just require all files in scoper.inc.php so that its set and forget. But that might be confusing with the globals.

**Comment by calvinalkan** [comment]
@swissspidy Implemented.

Also, I noticed by coincidence that your plugin uses an outdated commit in composer.lock (Probably because of the package rename). So just update the package again to 5.9 and it should be correct again.
